articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
]

modelForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
        class Meta():
            model = Article
            fields = '__all__'

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'index.html', context)

def create(request):

    if request.method == 'POST':
        form = ArticleForm(request.POST)
            
        if form.is_valid():
            form.save()
            return redirect('articles:index')

    else:
        form = ArticleForm(instance=article)

    context = {
        'form' : form,
    }

    return render(request, 'create.html', context)

def delete(request, id):
    if request.method == 'POST':
        article = Article.objects.get(id=id)
        article.delete()

    return redirect('articles:index')

def update(request, id):
    article = Article.objects.get(id=id)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=Article)

        if form.is_valid():
            form.save()
            return redirect('articles:index')

    else:            
        form = ArticleForm(instance=article)

    context = {
        'form' : form,
    }

    return render(request, 'update.html', context)

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}
<h2>create</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
    <h2>create</h2>
{% else %}
    <h2>update</h2>
{% endif %}


<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% for article in articles %}
        <h5>{{article.title}}</h5>
        <p>{{article.content}}</p>
        <p>{{article.created_at}}</p>
        {% comment %}
        <a href="{% url 'articles:delete' id=article.id %}">delete</a>
        {% endcomment %}

        <form action="{% url 'articles:delete' id=article.id %}" method="POSt">
            {% csrf_token %}
            <input type="submit" value="delete">
        </form>

        <a href="{% url 'articles:update' id=article.id %}">update</a>
        <hr>
    {% endfor %}
{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>홈그라운드입니다.</h2>
    <a href="{% url 'articles:create' %}">create</a>
    {% block body %}
    {% endblock %}
</body>
</html>